# Claves de identificación (te las da SonarCloud al crear el proyecto)
sonar.projectKey=jesuscorral_Concurso.homebrewer.cordoba
sonar.organization=jesuscorral

# Directorio principal del código
sonar.sources=master

# Exclusiones estrictas: No queremos analizar librerías ni archivos de test como código de producción
sonar.exclusions=**/node_modules/**, **/*.spec.ts, src/environments/**, e2e/**

# Dónde están los tests
sonar.tests=src,e2e
sonar.test.inclusions=**/*.spec.ts

# Ruta al reporte de cobertura (vital para las estadísticas de Test Coverage)
# Ajusta "nombre-de-tu-app" a lo que genere Angular en la carpeta coverage/
sonar.javascript.lcov.reportPaths==coverage/lcov.info