
# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI-CD_Firebase

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Install Dependencies
        run: npm install --save --legacy-peer-deps
        
      - name: Build
        run: npm run build --configuration production
        
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
          
  deploy:
    name: Deploy_to_firebase_hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: >-
            ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONCURSOHOMEBREWERCORDOB_6D540
            }}
          projectId: concursohomebrewercordob-6d540
          channelId:  ${{ secrets.CHANNEL_ID }}
